name: Deploy my lamba funciton

on:
  push:
    branches:
      - main
env:
  working-directory: function
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install libs
        working-directory: ${{ env.working-directory }}
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: create zipped bundle
        working-directory: ${{ env.working-directory }}
        run: zip -r ../${{ github.sha }}.zip .
      - name: archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sh }}.zip
